# ruby
#
# VERSION               0.0.1

FROM      ruby:alpine

MAINTAINER Gen Takahashi "gendosu@gmail.com"

# RUN chmod a+x /products/run.sh /products/entrypoint.sh
# RUN ./entrypoint.sh
# 
# ENTRYPOINT ["./entrypoint.sh"]
# CMD ./run.sh
# 
